plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android
}

android {
    compileSdk = 37

    defaultConfig {
        applicationId "ionut.andras.community.cgm.follower"
        minSdk = 28
        targetSdk = 37
        versionCode 97
        versionName '2.1.2'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testFunctionalTest false
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            // minifyEnabled true
            // proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
        }
    }
    namespace 'ionut.andras.community.cgm.follower'
}

dependencies {
    implementation libs.coreKtx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    testImplementation libs.junit
    testImplementation libs.junitJupiterApi
    testImplementation libs.junitJupiter

    androidTestImplementation libs.extJunit
    androidTestImplementation libs.espressoCore

    // Enable coroutines
    implementation libs.kotlinxCoroutinesAndroid
    implementation libs.lifecycleRuntimeKtx

    // Enable refresh on swipe down on the main window
    implementation libs.swiperefreshlayout

    // Enable drawing charts
    implementation libs.mpandroidchart

    // Enable object reflection
    implementation libs.kotlinReflect

    // Google Play services dependency for the SMS Retriever API
    implementation libs.playAuth
    implementation libs.playSms
}
