plugins {
    alias libs.plugins.android.application
    alias libs.plugins.jetbrains.kotlin.android
}

android {
    compileSdk 37

    defaultConfig {
        applicationId "ionut.andras.community.cgm.follower"
        minSdk 28
        targetSdk 37
        versionCode 97
        versionName '2.1.2'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testFunctionalTest false
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            // minifyEnabled true
            // proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    namespace 'ionut.andras.community.cgm.follower'
}

dependencies {
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    testImplementation libs.junit
    testImplementation libs.junit.jupiter.api
    testImplementation libs.junit.jupiter

    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // Enable coroutines
    implementation libs.kotlinx.coroutines.android
    implementation libs.lifecycle.runtime.ktx

    // Enable backward compatibility for HTML symbols
    implementation libs.core.ktx

    // Enable refresh on swipe down on the main window
    implementation libs.swiperefreshlayout

    // Enable drawing charts
    implementation libs.mpandroidchart

    // Enable object reflection
    implementation libs.kotlin.reflect

    // Google Play services dependency for the SMS Retriever API
    implementation libs.play.services.auth
    implementation libs.play.services.auth.api.phone
}